In [ ]:
import numpy as np
from typing_extensions import DefaultDict
import copy

In [ ]:
### Question 1 & Question2 LDU
table0 = [[0, 7, 8, 0], [11, 14, 14, 11], [2, 0, 3, 0], [0, 0, 5, 1], [0, 0, 0, 6]]
table1 = [[7, -1, 1], [1, 4, 3], [8, 1, 10]]
table2 = [[11, 14, 14, 11], [0, 7, 8, 0], [2, 0, 3, 0], [0, 0, 0, 6], [0, 0, 5, 1]]
table3 = [[8, 3, 7], [3, 2, 0], [9, 5, 3]]

def LDU(table):
  #table = np.array(table)
  rownum = len(table)
  columnnum = len(table[0])
  L = [[0 for i in range(rownum)] for j in range(len(table))]
  for k in range(rownum):
    L[k][k] = 1

  P = []
  for this in range(rownum):
    to_append = [0 for t in range(rownum)]
    to_append[this] = 1
    P.append(to_append)


  # check for row exchanges
  # go column by column to check for zeros
  for c in range(columnnum):
    exchange = 0
    empty = 1
    for r in range(rownum):
      if table[r][c] != 0:
        #print(table[r][c])
        empty = 0
    # if column not all zero, there might be a need to swap rows
    if empty == 0:
      d = 0
      while d < rownum and table[c][d] == 0:
        d += 1
      # d: row number of the top non zero element in the column
      if d > c:
        # swap rows if there are nothing to cancel out this top non-zero element
        temp = []
        for ii in range(columnnum):
          temp.append(table[c][ii])
        table[c] = table[d]
        table[d] = temp

        temp2 = []
        for ii in range(columnnum):
          temp2.append(P[c][ii])
        P[c] = table[d]
        P[d] = temp2

        for l in range(c):  # swap correposnding rows in l but only below diagonal
          temp3 = L[c][l]
          L[c][l] = L[d][l]
          L[d][l] = temp3

  print("table", table)
  print("P", P)

  for i in range(rownum):
    row = table[i]
    l_list = []
    for j in range(i):
      if row[j] != 0:
        m = row[j]/table[j][j]
        l_list.append(m)
        for k in range(columnnum):
          table[i][k] = table[i][k] - m*(table[j][k])
      else:
        l_list.append(0)
    for k in range(len(l_list)):
      L[i][k] = l_list[k]

  print("L")
  for i in range(len(L)):
    print(L[i])

  D = [[0 for i in range(len(L))]for j in range(len(L))]

  for i in range(min(rownum, columnnum)):
    if table[i][i] != 0:
      D[i][i] = table[i][i]
      for j in range(len(table[i])):
        table[i][j] = table[i][j]/D[i][i]

  print("D")
  for i in range(len(D)):
    print(D[i])

  print("U")
  for i in range(rownum):
    print(table[i])


  print("-"*40)


print("Question 1 testing")
LDU(table0)
print("a")
LDU(table1)
print("b")
LDU(table2)
print("c")
LDU(table3)

Question 1 testing
table [[11, 14, 14, 11], [0, 7, 8, 0], [2, 0, 3, 0], [0, 0, 5, 1], [0, 0, 0, 6]]
P [[0, 7, 8, 0], [1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]
L
[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0.18181818181818182, -0.36363636363636365, 1, 0, 0]
[0, 0, 1.4864864864864864, 1, 0]
[0, 0, 0, 1.5102040816326532, 1]
D
[11, 0, 0, 0, 0]
[0, 7, 0, 0, 0]
[0, 0, 3.3636363636363638, 0, 0]
[0, 0, 0, 3.972972972972973, 0]
[0, 0, 0, 0, 0]
U
[1.0, 1.2727272727272727, 1.2727272727272727, 1.0]
[0.0, 1.0, 1.1428571428571428, 0.0]
[0.0, 0.0, 1.0, -0.5945945945945946]
[0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0]
----------------------------------------
a
table [[7, -1, 1], [1, 4, 3], [8, 1, 10]]
P [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
L
[1, 0, 0]
[0.14285714285714285, 1, 0]
[1.1428571428571428, 0.5172413793103448, 1]
D
[7, 0, 0]
[0, 4.142857142857143, 0]
[0, 0, 7.379310344827587]
U
[1.0, -0.14285714285714285, 0.14285714285714285]
[0.0, 1.0, 0.689655172413793]
[0.0, 0.0, 1.0]
---------------

In [ ]:
### Question2 SVD
table1 = [[7, -1, 1], [1, 4, 3], [8, 1, 10]]
table2 = [[11, 14, 14, 11], [0, 7, 8, 0], [2, 0, 3, 0], [0, 0, 0, 6], [0, 0, 5, 1]]
table3 = [[8, 3, 7], [3, 2, 0], [9, 5, 3]]
##################################################
##################################################
def SVD(table):
  U, Sigma, VT = np.linalg.svd(table)
  print("U", U, "Sigma", np.diag(Sigma), "V", VT.transpose(), "-"*40, sep = "\n")

print("a")
SVD(table1)
print("b")
SVD(table2)
print("c")
SVD(table3)


a
U
[[-0.38887445  0.76978599 -0.50616814]
 [-0.22418008 -0.61196298 -0.75844881]
 [-0.89359944 -0.18146855  0.41054746]]
Sigma
[[14.2766668   0.          0.        ]
 [ 0.          5.55941537  0.        ]
 [ 0.          0.          2.69623553]]
V
[[-0.7071046   0.5980468  -0.37728386]
 [-0.09816334 -0.61141438 -0.78519833]
 [-0.70026213 -0.51818191  0.49104019]]
----------------------------------------
b
U
[[-0.92731392  0.23785583 -0.24014796 -0.08741628  0.13491051]
 [-0.32653768 -0.71841854  0.21238742  0.50925057 -0.26982102]
 [-0.09609671 -0.11500782  0.07653054 -0.64892688 -0.74200782]
 [-0.08902678  0.60317161  0.62519865  0.35795854 -0.33053076]
 [-0.12767809 -0.22417987  0.70745337 -0.42869784  0.4991689 ]]
Sigma
[[27.05677454  0.          0.          0.        ]
 [ 0.          7.73282316  0.          0.        ]
 [ 0.          0.          4.1758625   0.        ]
 [ 0.          0.          0.          3.56322468]]
V
[[-0.38410515  0.30860637 -0.59594071 -0.63409779]
 [-0.5643

In [ ]:
### Question3
# Input test matrix for SVD
input_matrix1 = [
    [7, -1, 1],
    [1, 4, 3],
    [8, 1, 10]
]

b1 = [2, 0, -20]

input_matrix2 = [
    [8, 3, 7],
    [3, 2, 0],
    [9, 5, 3]
]

b2 = [12, 1, 7]

b3 = [15, 14, 0]

def svd_solve(input_matrix, b, thresh):
  b = np.array(b)
  input_matrix = np.array(input_matrix)
  U, D, VT = np.linalg.svd(input_matrix) #resub
  print("U", U, "Sigma", np.diag(D), "V", VT.transpose(), sep = "\n")
  # with unique exact solution
  if abs(D[-1]) >= thresh:
    x = np.linalg.solve(input_matrix, b)
    print("unique exact solution x", x, sep = "\n")
  # if it has many or zero solutions
  else:
    for i in range(len(D)):
      if abs(D[i]) >= thresh:
        D[i] = 1/D[i]
    x_bar = np.matmul(np.matmul(VT.transpose(), np.matmul(np.diag(D), U.transpose())), b)
    Ax_bar = np.matmul(input_matrix, x_bar)
    # print("Ax_bar", Ax_bar, b, sep = "\n")
    flag = True
    for i in range(len(Ax_bar)):
      if abs(Ax_bar[i] - b[i]) >= thresh:
        flag = False
    # if there are zero solutions
    if not flag:
      print("There are 0 solutions, presenting SVD solution x_bar") #resub, add reason
      print("x_bar", x_bar, sep = "\n")
    else:
      x = np.linalg.solve(input_matrix, input_matrix[ :,0])
      x_bar_new = np.matmul(np.matmul(VT.transpose(), np.matmul(np.diag(D), U.transpose())), input_matrix[:, 0])  #resub, name clash
      x_n = np.subtract(x, x_bar_new) #resub, name clash
      print("There are multiple solutions") #resub, add reason
      print("x", x, "x_bar", x_bar, "all x", str(x_bar) + "+ k*" + str(x_n), sep = "\n")
  print("-"*40)


#U, D, V = np.linalg.svd(input_matrix)
#x = np.linalg.solve(input_matrix, b)
#print("U", U, "Sigma", np.diag(D), "V", V, "unique exact solution x", x, sep = "\n")

#print("-"*40)

#U2, D2, V2 = np.linalg.svd(input_matrix2)
#x2 = np.matmul(np.matmul(V2, np.matmul(np.diag(np.reciprocal(D2)), U2.transpose())), b2)
#Ax2 = np.matmul(input_matrix2, x2)
#print("U2", U2, "Sigma2", np.diag(D2), "V2", V2, "x2 bar", x2, "Ax2bar", Ax2, sep = "\n")

#print("-"*40)

t = 0.0001

print("a")
svd_solve(input_matrix1, b1, t)
print("b")
svd_solve(input_matrix2, b2, t)
print("c")
svd_solve(input_matrix2, b3, t)


a
U
[[-0.38887445  0.76978599 -0.50616814]
 [-0.22418008 -0.61196298 -0.75844881]
 [-0.89359944 -0.18146855  0.41054746]]
Sigma
[[14.2766668   0.          0.        ]
 [ 0.          5.55941537  0.        ]
 [ 0.          0.          2.69623553]]
V
[[-0.7071046   0.5980468  -0.37728386]
 [-0.09816334 -0.61141438 -0.78519833]
 [-0.70026213 -0.51818191  0.49104019]]
unique exact solution x
[ 1.  2. -3.]
----------------------------------------
b
U
[[-0.69924393  0.68659329 -0.19911699]
 [-0.20707103 -0.46111625 -0.86284031]
 [-0.68423645 -0.56210449  0.46460632]]
Sigma
[[1.53807062e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.66522525e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.84610916e-16]]
V
[[-0.80446843 -0.25906807 -0.53452248]
 [-0.38574666 -0.45644536  0.80178373]
 [-0.45169687  0.85119996  0.26726124]]
There are multiple solutions
x
[ 1. -0.  0.]
x_bar
[ 0.42857143 -0.14285714  1.28571429]
all x
[ 0.42857143 -0.14285714  1.28571429]+ k*[ 0.28571429 -0.42857143 -